#!/bin/zsh

confp="/home/$USER/.config"

opts=("bspwm
sxhkd
rofi")

choice=$(echo -e "${opts[@]}" | rofi -dmenu -theme '~/.config/rofi/launcher.rasi' window -i -p 'Open config file :')

function open {
    code $1
}

case $choice in
    bspwm)
        open "$confp/bspwm/bspwmrc"
        ;;
    sxhkd)
        open "$confp/sxhkd/sxhkdrc"
        ;;
    *)
        echo "Could not find this config file."
        ;;
esac
