#!/bin/zsh

confp="/home/$USER/.config"

shutdown=""
reboot=""
suspend=""
lock=""

opts=("$shutdown
$reboot
$suspend
$lock")

choice=$(echo -e "${opts[@]}" | rofi -dmenu -theme '~/.config/rofi/powermenu.rasi' window -i)

function open {
    code $1
}

case $choice in
    $shutdown)
        poweroff
        ;;
    $reboot)
        reboot
        ;;
    $lock)
        bspc quit
        ;;
    $suspend)
        systemctl suspend-then-hibernate
        ;;
    *)
        echo "Could not find $choice."
        ;;
esac
