vim.g.mapleader = " "

vim.opt.nu = true
vim.opt.relativenumber = true
vim.opt.numberwidth = 6
vim.opt.hlsearch=true
vim.opt.showtabline=0
vim.opt.title=true
vim.opt.splitbelow=true
vim.opt.splitright=true
vim.opt.ignorecase=true
vim.opt.smartcase=true
vim.opt.startofline=true
vim.opt.incsearch=true
vim.opt.hidden=true
vim.opt.scrolloff=5
vim.opt.autochdir=false
vim.opt.tabstop=2
vim.opt.shiftwidth=2
vim.opt.softtabstop=2
vim.opt.expandtab=false
vim.opt.autoindent=true
vim.opt.wrap=false
vim.opt.fileencoding='utf-8'
