#! /bin/sh

## STARTUP ##
start-if-not-running sxhkd
#start-if-not-running configure-monitors
#start-if-not-running no-beep
#start-if-not-running numlockx

case $(cat /proc/sys/kernel/hostname | awk '{print tolower($0)}') in
	# Use multiple monitors on my main computer
	chaos)
		bspc monitor DP-4 -d 1 2 3
		#bspc monitor DP-0 -d 4 5 6
		bspc monitor HDMI-0 -d 4 5 6 7 8 9
		;;
	# Use only one monitor on my laptop
	*)
		bspc monitor -d 1 2 3 4 5 6 7 8 9 10
		;;
esac

pgrep -x sxhkd > /dev/null || sxhkd &

## RICE
bspc config border_width       5 
bspc config window_gap          50
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config remove_unplugged_monitor true
bspc config center_pseudo-tiled false
bspc config focused_border_color "#fed270"
bspc config border_radius 25
bspc config pointer_motion_interval 7ms
#bspc rule -a Kupfer.py focus=on

#setxkbmap ca multix
noisetorch -i alsa_input.usb-FongLun_USB_Microphone_201605-00.analog-stereo
terminal --hold "paru" &
~/.screenlayout/default.sh &
nitrogen --restore
dunst &
bluetoothctl power on && bluetoothctl pairable on
picom &
eww open greeter &
