#! /bin/sh

## STARTUP ##
start-if-not-running sxhkd
start-if-not-running configure-monitors
start-if-not-running no-beep
start-if-not-running numlockx

case $(hostname | awk '{print tolower($0)}') in
	# Use multiple monitors on my main computer
	akali)
		bspc monitor DP-0 -d 1 2 3 10
		bspc monitor DP-4 -d 4 5 6
		bspc monitor HDMI-0 -d 7 8 9
		;;
	# Use only one monitor on my laptop
	*)
		bspc monitor -d 1 2 3 4 5 6 7 8 9 10
		;;
esac

pgrep -x sxhkd > /dev/null || sxhkd &

## RICE
bspc config border_width       3 
bspc config window_gap          12
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Kupfer.py focus=on

feh --bg-fill ~/.wallpapers/pilot.png
picom --experimental-backends --backend glx &
