XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
PATH="${PATH}:${HOME}/.local/bin/"
EDITOR="nvim"
VISUAL="nvim"
MANPAGER='nvim +Man!'

# NVM
NVM_DIR="$XDG_CONFIG_HOME/nvm"

# ZSH Configs
HISTFILE="$ZDOTDIR/.zhistory"
HISTSIZE=10000000
SAVEHIST=10000000
